sudo: required
language: node_js
node_js:
  - "10"

cache:
  directories:
  - node_modules

install:
  - npm install
  - npm install -g truffle
  - npm install -g ganache-cli
  
script:
  - ganache-cli
  - sleep 5
  - rm -rf build
  - truffle compile --all
  - truffle migrate --network development --reset
  - truffle test
  - kill -9 $(lsof -t -i:8545)
