sudo: required
language: node_js
node_js:
  - "10"

cache:
  directories:
  - node_modules

install:
  - npm install
  - npm install -g truffle@4.1.14
  - npm install -g ganache-cli
  
script:
  - ganache-cli 2> /dev/null 1> /dev/null &
  - sleep 5
  - truffle test
  - kill -9 $(lsof -t -i:8545)
