version: 2

# try to checkout pr merge if it exists, no op if not a pr build
checkout_pr_merge: &checkout_pr_merge
  run:
    name: try to checkout pr merge
    command: git fetch origin "+refs/pull/${CIRCLE_PULL_REQUEST##*/}/merge" && git checkout -qf FETCH_HEAD || echo "not pr build"

jobs:
  build:
    docker:
      - image: circleci/node:11.6.0
    steps:
      - checkout
      - <<: *checkout_pr_merge
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: run truffle test
          command: |
            npm install && npm install ganache-cli truffle@4.1.14
            node_modules/.bin/ganache-cli 2> /dev/null 1> /dev/null &
            node_modules/.bin/truffle test
            sudo apt-get install lsof && kill -9 $(lsof -t -i:8545)
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
