version: 2

# try to checkout pr merge if it exists, no op if not a pr build
checkout_pr_merge: &checkout_pr_merge
  run:
    name: try to checkout pr merge
    command: git fetch origin "+refs/pull/${CIRCLE_PULL_REQUEST##*/}/merge" && git checkout -qf FETCH_HEAD || echo "not pr build"

jobs:
  build:
    docker:
      - image: circleci/node:11.13.0
    steps:
      - checkout
      - <<: *checkout_pr_merge
      - restore_cache:
          # manually tag this key with modification date since we cache
          # truffle and ganache-cli during tests which will change package.json
          # remember to update restore_cache key and save_cache key for huge package updates
          key: npm-cache-04102019
      - run:
          name: install npm packages
          environment:
            GANACHE_VER: 6.4.2
            TRUFFLE_VER: 4.1.14
          command: npm install && npm install ganache-cli@$GANACHE_VER truffle@$TRUFFLE_VER
      - run:
          name: run truffle test
          command: |
            node_modules/.bin/ganache-cli 2> /dev/null 1> /dev/null &
            GANACHE_PID=$!
            node_modules/.bin/truffle test
            kill -9 $GANACHE_PID
      - save_cache:
          key: npm-cache-04102019
          paths:
            - "node_modules"
